samples: config/samples.tsv
units: config/units.tsv

EMU_PREBUILT_DB: 'silva'

guppy:
  GPU_basecalling: FALSE
  kit: 'SQK-NBD114-24'
  flowcell: "FLO-MIN114"
  config: 'dna_r10.4.1_e8.2_400bps_sup.cfg'